"""sections_results5.tex: phyloP conservation added to the splice model (discovery/splice_region_vus/phylop_lift.json)."""
import json
d=json.load(open('../discovery/splice_region_vus/phylop_lift.json'))
o=['\\section{Adding evolutionary conservation to the splice-region model}']
o.append(f"The best splice-region model so far is a logistic regression on PWM and MaxEntScan features. Neither feature sees conservation. We fetched phyloP100way at each variant position from the UCSC Genome Browser REST API for a stratified subsample of {d['n']:,} of the 9,235 modelled variants ({d['n_pathogenic']} pathogenic, {d['n_genes']:,} genes, {d['phylop_missing']} missing). The subsample keeps the class-by-site proportions of the full set; the API rate limit (one request per second) is why we did not fetch all 9,235.")
o.append(f"Median phyloP is {d['phylop_median_P']} at pathogenic and {d['phylop_median_B']} at benign positions. On its own, phyloP reaches AUROC {d['auc_phylop_alone']} ({d['per_site']['donor']['phylop_alone']} at donors, {d['per_site']['acceptor']['phylop_alone']} at acceptors). Added to logit+MaxEnt under gene-grouped 5-fold cross-validation repeated over 20 seeds, AUROC rises from {d['auc_logit_maxent_mean20']} to {d['auc_logit_maxent_phylop_mean20']}. A paired bootstrap on the averaged out-of-fold predictions gives a 95\\% interval for the gain of [{d['auc_diff_ci95_paired_bootstrap'][0]:+.4f}, {d['auc_diff_ci95_paired_bootstrap'][1]:+.4f}], which excludes zero.")
o.append('\\begin{table}[h]\\centering\\small\\begin{tabular}{lrrrr}\\hline site & $n$ & phyloP alone & logit+MaxEnt & + phyloP\\\\\\hline')
for s in ('donor','acceptor'):
    x=d['per_site'][s]; o.append(f"{s} & {x['n']} & {x['phylop_alone']:.4f} & {x['base']:.4f} & {x['with_phylop']:.4f}\\\\")
o.append(f"all & {d['n']} & {d['auc_phylop_alone']:.4f} & {d['auc_logit_maxent_mean20']:.4f} & {d['auc_logit_maxent_phylop_mean20']:.4f}\\\\")
o.append('\\hline\\end{tabular}\\caption{AUROC with and without phyloP (discovery/splice\\_region\\_vus/phylop\\_lift.json). Per-site values use the seed-averaged predictions.}\\end{table}')
o.append('The gain is concentrated at donor-region positions ($+3$ to $+6$), where the intronic consensus is short and conservation carries information the PWM misses. At acceptors (the polypyrimidine tract, $-3$ to $-14$), MaxEntScan already scores well and conservation adds little.')
o.append('\\paragraph{Caveat.} ClinVar submitters may cite conservation as supporting evidence (ACMG criteria PP3/BP4). Some of the gain may therefore be label circularity rather than new biology. We report the gain as modest and conditional on that caveat.')
o.append('\\paragraph{(F47) Model with conservation.} $\\mathrm{logit}\\,P(\\mathrm{path}\\mid x)=\\beta_0+\\boldsymbol\\beta^\\top\\mathbf z(x)+\\gamma\\,\\phi(x)+\\delta\\,\\phi(x)\\,\\mathbb 1[\\mathrm{donor}]$, with $\\mathbf z$ the standardised PWM/MaxEnt/position features and $\\phi$ the phyloP score; the interaction lets conservation matter differently at donors.')
o.append('\\paragraph{(F48) Paired bootstrap.} For resamples $b=1..B$ of variant indices $I_b$, $\\Delta_b=\\mathrm{AUC}(y_{I_b},\\hat p^{+}_{I_b})-\\mathrm{AUC}(y_{I_b},\\hat p^{0}_{I_b})$; the interval is the 2.5th and 97.5th percentile of $\\{\\Delta_b\\}$. Pairing on the same resample removes the shared sampling noise of the two models.')
open('sections_results5.tex','w').write('\n'.join(o)+'\n')
