"""sections_self_audit.tex: sugarcode self-audit chapter (post 2026-09-27 regime).
Sources: verification/selfaudit_20260927/*.json. No competition framing."""
import json
B = '../verification/selfaudit_20260927/'
inv = json.load(open(B+'inventory.json'))
t2 = json.load(open(B+'tier2_probes.json'))
ft = json.load(open(B+'FINAL_TABLE.json'))
s = ft['summary']
o = []
o.append('\\section{Self-audit of the full module stack}')
o.append('\\paragraph{Regime.} On 2026-09-27 the owner directed that this codebase be validated by internal audit rather than external model judges. This chapter is that audit: the full test suite executed by the auditor, an independent registry reconciliation, regeneration of every headline evidence number, and independent behavioral probes of every published-algorithm claim, followed by an import-, docstring-, and suite-level pass over all 95 modules. All artifacts (verbatim suite log, per-module table, probe scripts and results) are committed under verification/selfaudit\\_20260927/.')
o.append('\\subsection{Test suite}')
o.append(f"The configured suite ({s['suite']['collected']:,} tests) was executed on a clean copy of the audited tree: \\textbf{{{s['suite']['passed']:,} passed, {s['suite']['failed']} failed, {s['suite']['skipped']} skipped}} in 86 seconds. The single failure is the repository's own drop-54 meta-gate (zero empty function bodies), which flags three ellipsis protocol stubs in the self-improvement subsystem; each stub has a working concrete implementation directly below it, so the failure is a style-gate violation, not a functional defect, and is reported as an honest fail. The eight skips are all optional-dependency gates (ViennaRNA, torch, pydeseq2, primer3, vina $\\times$2, an uncached image dataset, and a setuptools version probe).")
o.append('\\subsection{Registry and headline regeneration}')
o.append(f"The product registry reconciles exactly: {inv['modules_total']} registered slugs, {inv['modules_total']} package directories, no orphans in either direction. The consolidated evidence report (the repository's own headline numbers for its clinically validated splice module) was regenerated independently from the hermetic fixtures: 2,720 unique pathogenic and 86 benign variants; canonical U2 sites 2,414/2,414 called loss; AT-AC sites 16/16 called loss; benign specificity 85/86; the GC-donor, VUS, conflicting-classification, exonic-window, cryptic-recall and ESRseq numbers all reproduce exactly, including the two reported honest nulls.")
o.append('\\subsection{Independent probes of published-algorithm claims}')
o.append('Each published-algorithm claim was probed against an independent computation, not the repository\'s own tests: flux balance analysis reproduces the identical optimum under an independent LP solver call (15.0 vs 15.0); the codon adaptation index matches an independent Sharp--Li recomputation to machine precision under the published Met/Trp/stop exclusion convention; the anisotropic network model matches an independently rebuilt Hessian exactly (six rigid-body zero modes, first nonzero frequency 0.1329 in both); the stochastic expression simulator is a true Gillespie SSA whose steady-state means match the analytic values; the Hill promoter term returns exactly the analytic half-maximum at $[R]=K_d$; the TASEP and chemical-Langevin engines are deterministic under fixed seed with physically bounded densities; the Chou--Fasman predictor scores poly-alanine 75\\% helix and poly-proline/glycine zero.')
o.append('\\subsection{Per-module verdicts}')
o.append(f"All {s['modules']} modules pass at their verification level: {sum(1 for r in ft['per_module'] if 'tier1' in r['level'])} at evidence-headline level, {sum(1 for r in ft['per_module'] if 'tier2' in r['level'])} at independent behavioral-probe level, and the remainder at import + docstring + suite level ({s['suite']['passed']:,} suite tests passing). One claim-level failure: the status ledger attributes Hill-kinetics ODE models to the gene-analysis module, but no Hill code exists there (the kinetics live in the synthetic-biology and virtual-cell modules); the module itself passes. {s['n_without_docstring']} of 95 modules lack module-level docstrings, documenting method via header comments instead (function-level documentation ranges 8--100\\%). One module's six passing tests live outside the configured test paths (a suite-wiring gap, not a failure).")
o.append('\\subsection{Limitations}')
o.append('(i) Headline rows beyond the regenerated evidence report are suite-locked and were not individually re-verified against live external sources. (ii) 73 heuristic-tier modules expose no zero-argument probe entry, so their behavioral coverage is the suite rather than an auditor probe. (iii) The Ensembl-dependent routes remain Missing per the repository\'s own ledger and were not re-tested. (iv) The audited tree is read-only for the auditor; the five documentation findings (stale status test count, the Hill misattribution, one method-wording imprecision, the docstring gap, the test-wiring gap) are reported for the maintainers\' lane rather than fixed in place.')
open('sections_self_audit.tex','w').write('\n'.join(o)+'\n')
print('written', sum(len(x) for x in o), 'chars')
