"""Generate sections_results3.tex (DE, enrichment, PPI, alignment) from committed benchmark JSON."""
import json, matplotlib; matplotlib.use('Agg'); import matplotlib.pyplot as plt
B='../benchmarks/'
def esc(s): return str(s).replace('_','\\_').replace('&','\\&').replace('%','\\%').replace('#','\\#')
de=json.load(open(B+'sweep_de_pydeseq2.json')); en=json.load(open(B+'sweep_dex_enrichment.json'))
st=json.load(open(B+'sweep_dex_string_ppi.json'))['result'][0]; rc=json.load(open(B+'sweep_dex_reactome.json'))
pa=json.load(open(B+'sweep_align_parasail.json'))
o=[]
o.append('\\section{Differential expression and pathway-level follow-up}')
o.append(f"We re-ran the airway dexamethasone experiment (GEO GSE52778) through the sugarcode DESeq2 path and through PyDESeq2. Of {de['n_genes_tested']:,} genes passing the count filter, the paired design $\\sim$cell$+$dex gave {de['pydeseq2_paired_n_sig']:,} genes at adjusted $p<0.05$ and the unpaired design gave {de['pydeseq2_unpaired_n_sig']:,}. Size factors agreed to a maximum relative difference of {de['size_factor_max_rel_diff']:.1e} (benchmarks/sweep\\_de\\_pydeseq2.json).")
o.append('\\paragraph{(F25) Negative-binomial GLM.} For gene $g$ and sample $j$, $K_{gj}\\sim\\mathrm{NB}(\\mu_{gj},\\alpha_g)$ with $\\mu_{gj}=s_j q_{gj}$ and $\\log_2 q_{gj}=\\sum_r x_{jr}\\beta_{gr}$, so $\\mathrm{Var}(K_{gj})=\\mu_{gj}+\\alpha_g\\mu_{gj}^2$.')
o.append('\\paragraph{(F26) Median-of-ratios size factor.} $s_j=\\mathrm{median}_{g:K_{g\\cdot}>0}\\, K_{gj}\\big/\\big(\\prod_{v=1}^{m}K_{gv}\\big)^{1/m}$.')
o.append('\\paragraph{(F27) Wald statistic.} $W_g=\\hat\\beta_{g,\\mathrm{dex}}/\\mathrm{SE}(\\hat\\beta_{g,\\mathrm{dex}})$, compared with $N(0,1)$; the paired design removes the cell-line effect from the residual variance, which is why it finds more genes than the unpaired design.')
o.append('\\subsection{Gene-set over-representation}')
o.append(f"We took the {en['n_query']} dex-induced genes (adjusted $p<0.05$, $\\log_2\\mathrm{{FC}}>1$) and tested them against the {en['n_background']:,} tested genes with g:Profiler (version {esc(en['gprofiler_meta_version'])}, g:SCS correction). {en['n_significant_terms']} terms passed. The top terms are broad (Table~\\ref{{tab:gost}}).")
o.append('\\paragraph{(F28) Hypergeometric tail.} With background size $M$, term size $K$, query size $n$ and overlap $k$, $p=\\sum_{i\\ge k}\\binom{K}{i}\\binom{M-K}{n-i}\\big/\\binom{M}{n}$, and fold enrichment $=(k/n)/(K/M)$.')
o.append('\\begin{table}[h]\\centering\\small\\begin{tabular}{llrrr}\\hline Source & Term & overlap & size & $p_{\\mathrm{adj}}$\\\\\\hline')
for t in en['top_terms'][:12]:
    o.append(f"{esc(t['source'])} & {esc(t['name'][:48])} & {t['intersection']} & {t['term_size']} & {t['p']:.2g}\\\\")
o.append('\\hline\\end{tabular}\\caption{Top g:Profiler terms for dex-induced genes (benchmarks/sweep\\_dex\\_enrichment.json).}\\label{tab:gost}\\end{table}')
gc=en['glucocorticoid_terms']
o.append('\\paragraph{Negative result.} The terms one would expect for a glucocorticoid are enriched but do not survive correction:')
o.append('\\begin{table}[h]\\centering\\small\\begin{tabular}{lrrrr}\\hline Term & overlap & size & fold (approx.) & $p_{g:SCS}$\\\\\\hline')
for t in gc:
    o.append(f"{esc(t['name'][:50])} & {t['intersection']} & {t['term_size']} & {t.get('fold_enrichment_approx','--')} & {t['p_gSCS']:.2g}\\\\")
o.append('\\hline\\end{tabular}\\caption{Glucocorticoid terms: large fold change, not significant. '+esc(en['glucocorticoid_note'][:0])+'}\\end{table}')
o.append('The small term sizes (tens of genes) and the strong multiple-testing burden explain this: a 7-fold enrichment built on 9 genes is not enough evidence after g:SCS correction. We report it as a negative rather than as confirmation of the expected biology.')
o.append('\\subsection{Reactome pathways}')
t0=rc['top25']
o.append(f"Reactome AnalysisService mapped the query to {rc['pathways_found']:,} pathways ({rc['identifiers_not_found']} identifiers not found). No pathway reached FDR$<0.05$; the smallest FDR was {min(t['fdr'] for t in t0):.2f}. Reactome uses its whole human gene universe as background, which is a further caveat.")
o.append('\\begin{table}[h]\\centering\\small\\begin{tabular}{lrrrr}\\hline Pathway & found & total & $p$ & FDR\\\\\\hline')
for t in t0[:10]:
    o.append(f"{esc(t['name'][:50])} & {t['found']} & {t['total']} & {t['p']:.2g} & {t['fdr']:.2f}\\\\")
o.append('\\hline\\end{tabular}\\caption{Top Reactome pathways (benchmarks/sweep\\_dex\\_reactome.json).}\\end{table}')
o.append('\\paragraph{(F29) Benjamini-Hochberg.} For ordered $p_{(1)}\\le\\dots\\le p_{(m)}$, $q_{(i)}=\\min_{j\\ge i}\\min\\{1,\\,m\\,p_{(j)}/j\\}$.')
o.append('\\subsection{Protein interaction network}')
o.append(f"STRING's PPI enrichment test on the top 300 dex-induced genes mapped {st['number_of_nodes']} proteins with {st['number_of_edges']} edges against {st['expected_number_of_edges']} expected (average degree {st['average_node_degree']}, local clustering {st['local_clustering_coefficient']}), reported $p$ below floating-point resolution. Caveat: STRING's expectation uses a genome-wide background, so genes expressed in airway smooth muscle may be more connected than random genes regardless of dex.")
o.append('\\paragraph{(F30) Edge enrichment ratio.} $E=\\,$observed edges$/$expected edges$=%d/%d=%.2f$.' % (st['number_of_edges'],st['expected_number_of_edges'],st['number_of_edges']/st['expected_number_of_edges']))
gs=json.load(open(B+'sweep_dex_gsea_hallmark.json')); go=json.load(open(B+'sweep_dex_goatools.json'))
nw=json.load(open(B+'sweep_dex_string_network.json'))
o.append('\\subsection{Network hubs}')
o.append(f"We pulled the STRING network among the same genes and analysed it with {esc(nw['tool'])}: {nw['n_nodes']} connected nodes, {nw['n_edges']} edges, a largest component of {nw['largest_component']} nodes. The highest-degree hubs are "+', '.join(f"{esc(g)} ({d})" for g,d in nw['top_degree'][:6])+f". Of ten canonical glucocorticoid-receptor targets fixed before the run, {len(nw['gr_targets_in_network'])} are in the network, with mean degree {nw['gr_mean_degree']:.2f} against {nw['network_mean_degree']:.2f} overall; a degree permutation test ({nw['n_perm']:,} draws) gives $p={nw['perm_p_gr_degree']:.3f}$. With eight genes this is weak evidence and we do not claim it as a finding.")
o.append('\\paragraph{(F34) Betweenness centrality.} $C_B(v)=\\sum_{s\\ne v\\ne t}\\sigma_{st}(v)/\\sigma_{st}$, with $\\sigma_{st}$ the number of shortest $s$--$t$ paths and $\\sigma_{st}(v)$ those through $v$.')
o.append('\\paragraph{(F35) Permutation $p$-value.} $\\hat p=(1+\\#\\{b: T_b\\ge T_{obs}\\})/(1+B)$, which is never zero and is valid for any fixed statistic $T$.')
o.append('\\subsection{Rank-based test: preranked GSEA}')
o.append(f"Threshold-based over-representation throws away the ranking. We therefore ran preranked GSEA ({esc(gs['tool'])}) on all {gs['n_ranked']:,} ranked genes against the {gs['n_tested']} MSigDB Hallmark sets. {gs['n_fdr_lt_0.05']} set passed FDR$<0.05$ and {gs['n_fdr_lt_0.25']} passed FDR$<0.25$ (Table~\\ref{{tab:gsea}}). The one significant set, Adipogenesis, is a known glucocorticoid-driven programme; this is a modest, single-set result.")
o.append('\\paragraph{(F32) Enrichment score.} With ranked scores $r_j$ and set $S$, $P_{hit}(i)=\\sum_{j\\le i, g_j\\in S}|r_j|/N_R$, $P_{miss}(i)=\\sum_{j\\le i, g_j\\notin S}1/(N-N_S)$, and $ES=\\max_i|P_{hit}(i)-P_{miss}(i)|$ (signed).')
o.append('\\paragraph{(F33) Normalised ES.} $NES=ES/\\overline{ES_{\\pi}^{\\pm}}$, the mean of same-sign permutation scores; FDR compares $NES$ with the permutation distribution of all sets.')
o.append('\\begin{table}[h]\\centering\\small\\begin{tabular}{lrrr}\\hline Hallmark set & NES & nominal $p$ & FDR\\\\\\hline')
for t in gs['all'][:10]: o.append(f"{esc(t['term'])} & {t['nes']:.2f} & {t['nom_p']:.3g} & {t['fdr']:.3f}\\\\")
o.append('\\hline\\end{tabular}\\caption{Preranked GSEA, Hallmark (benchmarks/sweep\\_dex\\_gsea\\_hallmark.json).}\\label{tab:gsea}\\end{table}')
o.append('\\subsection{Independent GO cross-check with goatools}')
gcs=[t for t in go['glucocorticoid_terms'] if t['name']=='cellular response to glucocorticoid stimulus'][0]
o.append(f"goatools (Fisher exact, BH, propagated counts, GOA human annotations, background of {go['n_population']:,} expressed genes, {go['n_study']} study genes) found {go['n_sig_bp_fdr05']} GO:BP terms at FDR$<0.05$. Of g:Profiler's {go['gprofiler_top_bp_total']} top BP terms, {len(go['gprofiler_top_bp_in_goatools_sig'])} are also significant here. The glucocorticoid term (cellular response to glucocorticoid stimulus, {gcs['study']}/{gcs['pop']} genes) reaches FDR {gcs['fdr']:.3f} under BH but fails g:Profiler's g:SCS. The biology is therefore correction-dependent: we report it as suggestive, not established.")
o.append('\\begin{table}[h]\\centering\\small\\begin{tabular}{llrrr}\\hline GO & Term & study & pop & FDR\\\\\\hline')
for t in go['top25'][:10]: o.append(f"{t['go']} & {esc(t['name'][:42])} & {t['study']} & {t['pop']} & {t['fdr']:.2g}\\\\")
o.append('\\hline\\end{tabular}\\caption{goatools GO:BP (benchmarks/sweep\\_dex\\_goatools.json).}\\end{table}')
o.append('\\section{Pairwise alignment against parasail}')
g,l=pa['global'],pa['local']
o.append(f"We aligned all {pa['n_pairs']} pairs of {pa['n_seqs']} protein sequences with sugarcode and parasail {esc(pa['tool'].split()[-1])}. With parasail's open penalty set to 11 the scores matched exactly for {g['exact_vs_parasail_open11']}/{g['n']} global and {l['exact_vs_parasail_open11']}/{l['n']} local pairs. With open penalty 12 only {g['exact_vs_parasail_open12']} and {l['exact_vs_parasail_open12']} matched (maximum difference {g['max_abs_diff_open12']:.0f} and {l['max_abs_diff_open12']:.0f}). This fixes the convention: sugarcode's gap\\_open$=-11$ is the cost of the first gap residue, i.e. parasail open 11.")
o.append('\\paragraph{(F31) Affine gap cost.} A gap of length $L$ costs $\\gamma(L)=o+(L-1)e$ under sugarcode and parasail open$=11$; under the alternative convention $\\gamma(L)=o+Le$, which explains the open-12 mismatch.')
fig,ax=plt.subplots(1,2,figsize=(8,3))
ax[0].barh([t['name'][:30] for t in t0[:8]][::-1],[t['fdr'] for t in t0[:8]][::-1]); ax[0].axvline(0.05,color='r',ls='--'); ax[0].set_xlabel('Reactome FDR'); ax[0].tick_params(labelsize=6)
ax[1].bar(['observed','expected'],[st['number_of_edges'],st['expected_number_of_edges']],color=['C0','0.6']); ax[1].set_ylabel('STRING edges')
plt.tight_layout(); plt.savefig('figs/dex_pathways.pdf')
o.append('\\begin{figure}[h]\\centering\\includegraphics[width=0.95\\textwidth]{figs/dex_pathways.pdf}\\caption{Left: Reactome FDRs for the top pathways; the red line is 0.05. Right: STRING observed versus expected edges.}\\end{figure}')
open('sections_results3.tex','w').write('\n'.join(o)+'\n')
